site_name: SmartCLIDE
site_url: https://eclipse-researchlabs.github.io/smartclide-docs/
plugins:
  - search:
  - multirepo:
nav:
  - Home: 'index.md'
  - Context Handling: '!import https://github.com/eclipse-researchlabs/smartclide-context?branch=main'
theme: readthedocs
copyright: Copyright &copy; 2022 The SmartCLIDE Consortium