site_name: SmartCLIDE Docs
site_url: https://eclipse-researchlabs.github.io/smartclide-docs/
plugins:
  - search:
  - multirepo:
nav:
  - Home: 'index.md'
  - Context Handling: '!import https://github.com/eclipse-researchlabs/smartclide-context?branch=main'
theme: readthedocs
copyright: Copyright &copy; 2022 The SmartCLIDE Consortium

extra:
  version: v1.0
  social:
    - icon: fontawesome/brands/twitter
    - link: https://twitter.com/squidfunk